spaceros/Dockerfile

The recent version change of cyclonedds introduced a .y file and a dependency on bison to compile it. 

Fix spaceros base docker image build

---

moveit2/moveit2.repos

urdfdom and urdfdom_headers already included in the base Space ROS image.

Update some of the MoveIt2 dependencies

---

demo_spaceros/run.sh
moveit2/README.md
moveit2/run.sh
moveit2_tutorials/README.md
moveit2_tutorials/run.sh
spaceros/README.md
spaceros/run.sh

- Ensure there is a run.sh script in each directory.
- Update READMEs accordingly
- No longer need info about setup for GUI apps

Introduce a consistent set of run scripts

---

demo_spaceros/README.md
moveit2/README.md
moveit2_tutorials/README.md
spaceros/Dockerfile
spaceros/README.md

I read through the READMEs again, following the instructions and found a few spots I missed on the previous update. Also one statement that was incorrect in the spaceros Dockerfile.

Fix a couple missed spots in the READMEs; fix a WORKDIR statement

---

demo_spaceros/Dockerfile
demo_spaceros/excluded-pkgs.txt
moveit2/Dockerfile
spaceros/Dockerfile

* Set the base distribution in the spaceros docker file (set the ROSDISTRO environment variable)
* Use ROSDISTRO instead of hard-coded distro names in the Dockerfiles
* Add generate_parameter_library to the excluded list of packages

Update for Humble

---

demo_spaceros/README.md

Clarify build instructions for demo_spaceros

---

moveit2/Dockerfile
moveit2/run.sh
space_robots/Dockerfile
space_robots/run.sh
spaceros/Earthfile
spaceros/README.md
spaceros/build.sh
spaceros/run.sh

Updated all demos to use rocker to run the built images. Verified things work as documented (except moveit2_tutorials, which will be merged with moveit2 in another PR).

Using rocker

---

.github/workflows/earthly-build.yaml
spaceros/Earthfile

This PR addresses some deprecation warnings due to evolutions in GitHub Actions as well as a few cleanups in order to fix steps succeeding without performing their tasks.

Update GitHub Actions flow

---

.github/workflows/docker-build.yml

This action builds the space_robots image using the latest published `osrf/space-ros:latest` image as a base.

Add workflow to build space_robots image.

---

spaceros/Earthfile

This fixes issue #45 by starting the workspace step from the sources step

Start workspace step from end of sources step

---

spaceros/Earthfile

Update the OpenGL version to avoid an empty graphics screen.

---

space_robots/README.md

Add instructions for building of spaceros and moveit2 images to the space_robots README

Update build instructions

---

space_robots/demo_manual_pkgs.repos

Pin gps_msgs version

---

moveit2/run.sh
nav2_demo/run.sh
navigation2/run.sh
space_robots/run.sh
spaceros/README.md
spaceros/run.sh

Remove rocker from run.sh files to fix issue #146

Remove rocker - fix issue #146

---

.github/workflows/pr.yaml

Add commit message checker CI job (#185)

---

rtems/README.md

Update RTEMS documentation url (fixes #211)

---

navigation2/Dockerfile
navigation2/build.sh
navigation2/navigation2.repos

update nav2 image to jazzy (#226)

update nav2 image to jazzy (#226)

---

moveit2/Dockerfile
navigation2/Dockerfile
space_robots/Dockerfile

Fixes #206 
Alternatively, we could also try `sudo -E` to preserve environment variables in `sudo` 
[related](https://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo)

Use sudo -E to preserve DEBIAN_FRONTEND=noninteractive (#206)

---

moveit2/Dockerfile
navigation2/Dockerfile

Update the GPG keys in the repo (fix #249)

Update the GPG keys (fix issue #249)

---

moveit2/Dockerfile
moveit2/README.md
moveit2/build.sh
moveit2/entrypoint.sh
moveit2/run.sh
nav2_demo/Dockerfile
nav2_demo/README.md
nav2_demo/entrypoint.sh
nav2_demo/run.sh
navigation2/Dockerfile
navigation2/README.md
navigation2/build.sh
navigation2/entrypoint.sh
navigation2/run.sh
space_robots/Dockerfile
space_robots/README.md
space_robots/entrypoint.sh
space_robots/run.sh

Resolves #198.
This is a work in progress until https://github.com/space-ros/space-ros/pull/186 and the related PRs are merged and released in the base `space-ros` package. We should modify the demo images as they will be correspondingly smaller.

Modify demos to use the lightweight images
