space-ros/docker

moveit2/Dockerfile, moveit2/moveit2.repos, spaceros/Dockerfile
* The package versions now match Rolling (intend to keep in sync). This will help to keep compiles working as the latest MoveIt2 code should be building against Rolling. 
* I've added the branch info to each entry in the moveit2.repos file for future reference; makes it convenient to browse the other repos if inspecting versions (to make sure I'm looking at the right branch). 
* Also, there now seems to be no need to manually zip the .egg file from the egg-info directory, so removed that.
* Added rosidl_typesupport_fastrtps_cpp to the skip-keys list.
=> Update the docker scripts and the versions of dependent packages

spaceros/Dockerfile
The Docker cache will only be invalidated if the url or downloaded contents change.
I also moved the url into a build argument so it could be overridden for testing.
=> Use ADD to fetch an updated repos file on each build.

spaceros/Dockerfile
Key rotation in the nvidia repositories has not yet been propagated to
the baseimage used by this project. For now, update the key ourselves, we should be able to periodically check the base image for updates that may allow us to revert this
change. 
If we're "lucky" the build will fail when apt-key del has no key to remove.
=> Add key update to workaround outdated base image.

README.md, demo_spaceros/README.md
Since the demo dockerfile does not explicitly refer back to the [demo repo](https://github.com/space-ros/demo), it would be more straightforward to put the instructions under the dockerfile README.
Added a link to the main README
=> edited demo readme

demo_spaceros/Dockerfile, demo_spaceros/README.md, demo_spaceros/entrypoint.sh, moveit2/Dockerfile, moveit2/README.md, moveit2/entrypoint.sh, moveit2_tutorials/Dockerfile, moveit2_tutorials/README.md, moveit2_tutorials/entrypoint.sh, spaceros/Dockerfile, spaceros/README.md, spaceros/entrypoint.sh
Although the "_ws" is a convention for workspaces, I really don't see any benefit to using it since it's just a directory that contains ROS 2 packages. In fact, I'd rather see uniformity in the directory names under 'src' so that it doesn't matter if the directory contains ROS 2 packages or not. For example:
/home/spaceros-user/
src/
/ikos
/spaceros
/moveit2
/moveit2_tutorials
/curiosity_demo
etc.
I could be convinced otherwise, but this seems cleaner to me. 
=> Update the workspace names

renode_rcc/Dockerfile, renode_rcc/README.md, renode_rcc/build.sh, renode_rcc/run.sh, rtems/Dockerfile, rtems/README.md, rtems/build.sh, rtems/example/src/CMakeLists.txt, rtems/example/src/main.cpp, rtems/run.sh
Instead of having a separate repository for the docker-based RTEMS-related work, bring it into the docker repo.
No changes yet to the contents, except the README, which was split across the two directories. Subsequent PRs will update these directories to ensure uniformity with other directories here. 
=> Incorporate the RTEMS and Renode docker work into the docker repo

.github/workflows/earthly-build.yaml
Deprecation warnings are showing up because of changes to the nodejs version used internally by the checkout action.
=> Update checkout action to v3

.github/workflows/earthly-build.yaml
Image pushes weren't being triggered for the scheduled runs.
=> Update image push conditions.

.github/workflows/docker-build.yml
Adds build actions: on 'pull_request'  will automatically run a build each time a PR is opened,  and on 'workflow_dispatch' which will enable a "Run workflow" button on the Actions tab.
Addresses parts of #55
=> Add build actions on pull request and on demand

.github/workflows/docker-build.yml, moveit2/moveit2_tutorials.repos
Attempt to fix #64. The upstream branch was updated back to `humble`.
=> Update moveit_task_constructor branch back to *humble*

.github/workflows/markdown-link-check.yml, README.md, moveit2/README.md, zynq_rtems/README.md
Add the markdown-link-check workflow in GHA. Fixes #72 
Note that this should fail due to #68, until that is fixed. I'll add a second commit to fix that once this runs and flags the issue.
=> Add markdown-link-check workflow

moveit2/build.sh, space_robots/build.sh, spaceros/build.sh
Adding `set -eo pipefail` to the space_robots workflow to fix #75
=> Add pipefail to space_robots build so that it fails on error

space_robots/demo_manual_pkgs.repos
This source dependency is missing and failing the build. Closes #87.
=> Add vision_msgs to demo deps (#87)

moveit2/Dockerfile
Closes #77.
This is a common hack to avoid running out of memory while building a large C++ codebase. However, it's unnecessary in an era where users just need to be educated to configure `zram` on their system.
=> Don't limit parallel workers in moveit2 build (#77)

moveit2/README.md
I was doing some testing with these Docker images to give an official MoveIt maintainer sign-off for working MoveIt2 images.
I was able to run both the MoveIt2 Tutorials RViz example as per the `moveit2` image, and also the Canadarm demo in the `space_robots` image.
Just submitting a few small tweaks based on my trying to follow the instructions, but otherwise 👍🏻 
Closes https://github.com/space-ros/docker/issues/85
---
Quick question -- can I also remove all the `$` from all the README Instructions, like
```
$ ./run.sh
```
because it makes it annoying to copy paste -- I have to manually select the text or remove the first few characters instead of copying the entire line.
=> Point users to `space_robots` demo at the end of `moveit2` README (#85)

moveit2/README.md, renode_rcc/README.md, rtems/README.md, space_robots/README.md, spaceros/README.md, zynq_rtems/README.md
This commit styles the READMEs to not include the dollar prompt in code blocks denoting commands to type, to make it easier to copy-and-paste those in a terminal.
This also adds bash as the language of the code blocks, so that github styles those correctly.
Originally submitted by @sea-bass. Authorship information retained. I'm filing these to make his job a bit easier.
=> Improve style of shell code blocks in README (#110).

spaceros/README.md
This PR replaces uses of single quote symbols `'` with backticks when surrounding commands or command arguments, so that they are formatted correctly.
The commit incorporates changes implemented by @sea-bass, as well as others. To retain the authorship information correctly, it's filed as two separate commits instead of one.
=> Replace single quotes with backticks (#114).

moveit2/README.md, space_robots/README.md
Fix two typos (wrong word, missing article).
Filed on behalf of @sea-bass (I'm just the messenger). Authorship information retained.
=> Fix typos in READMEs (#111).

moveit2/README.md, renode_rcc/README.md, space_robots/README.md, spaceros/README.md, zynq_rtems/README.md
Having long sentences in READMEs makes them harder to change, and also makes processing the diffs harder (among other disadvantages).
This commit implements the one-sentence-per-line principle, by placing different sentences in separate lines in the README.
This PR inherits from one originally filed in #84. To retain authorship information correctly, this PR incorporate @sea-bass' changes in one commit, and additional changes in a separate commit.
=> Place sentences in separate lines in READMEs (#113).

moveit2/Dockerfile, renode_rcc/Dockerfile, rtems/Dockerfile, space_robots/Dockerfile, zynq_rtems/Dockerfile
I've added
```
--mount=type=cache,target=/var/cache/apt,sharing=locked \
--mount=type=cache,target=/var/lib/apt,sharing=locked \
```
in front of every operation that modifies the Apt lists. This ensures that the Apt lists will not end up in the layers and in the final image, while preserving the lists between operations so it doesn't slow down the build.
=> Use Docker cache mounts for Apt lists

spaceros/Earthfile
This PR fixes https://github.com/space-ros/docker/issues/103.
Space ROS's main Earthfile's build-testing procedure is invoked in CI to push results of tests and static code analysis. Currently, for all packages cobra-autosar.sarif results are empty. This is because cobra or some dependent executables are not found when colcon test command is invoked.
This PR prefixes the call to colcon test in the Earthfile by a call to source that brings all the necessary tools and dependencies into scope.
Note that re-enabling cobra significantly extends `build-testing` time from 1hr 13 minutes to 1hr 55 minutes on my local machine [^1].
Check the files before and after for comparison:
* [cobra-autosar file prior to fix](https://gist.github.com/xfiderek/46bd91b0c6f65277284ab944d16e82e2)
* [cobra-autosar …
=> Ensure that cobra is executed during tests (#103).

spaceros/Earthfile
IKOS is one of the tools that Space ROS includes to perform static analysis of ROS 2 applications. Although ament_ikos is provided with the docker image, IKOS itself is not, rendering the former useless and leaving it to users to compile and install IKOS prior to being able to use it.
This commit modifies the spaceros Earthfile to install IKOS globally in the system.
=> Make IKOS available in the spaceros image (#99).

.github/workflows/earthly-build.yaml
This commit disables pushes of the spaceros docker image up to Docker Hub on the main branch, and it enables pushes on tags. It also enables manually triggering the build job.
This will help ensure that only stable version are pushed to Docker Hub.
=> Update GA to push image to Docker Hub only on tags (#93).

spaceros/Earthfile, spaceros/README.md, spaceros/entrypoint.sh
This PR addresses https://github.com/space-ros/docker/issues/138, by adjusting the Earthfile, entrypoint.sh, and README.md, so that IKOS tutorial is runnable.
=> Fix IKOS tutorial (#138).

.github/workflows/earthly-build.yaml, spaceros/Earthfile
This uses `github.ref_name` as a tag when the image is pushed to Dockerhub, which fixes #148 
The only way I know to test this is to add a tag to the repo and see if it works. However if it does push to Dockerhub, I can't remove the image if it's tagged incorrectly. I'm open to other suggestions how to test it.
=> Auto tag release image (fix #148)

moveit2/moveit2-pkgs.txt
Resolves #153 
Fixing the build due to new dependencies in MoveIt Task Constructor, as added in https://github.com/moveit/moveit_task_constructor/pull/560
=> Add py_binding_tools to MoveIt2 packages to fix humble build

moveit2/Dockerfile, moveit2/moveit2_tutorials.repos, navigation2/Dockerfile, navigation2/navigation2.repos, space_robots/demo_manual_pkgs.repos
Resolves https://github.com/space-ros/docker/issues/163.
Should be purely cosmetic changes to match the updated organizations post migration.
=> Update GH Organizations for MoveIt and Nav2 Repos

renode_rcc/Dockerfile
The [upstream repository](https://github.com/antmicro/renode-rtems-leon3) used by this Dockerfile updated their internal dependencies (https://github.com/antmicro/renode-rtems-leon3/commit/4e962e4783cb29c38ccdf8a11e879788f10c09a1) which are referenced by version number here: https://github.com/space-ros/docker/blob/ad020b80406974bb494f04a6a3f8216273a5489e/renode_rcc/Dockerfile#L39
I considered pinning the upstream version given the magic-numbers at play, but because git doesn't support cloning by commit hash, (and the upstream works without branches, tags, or releases), I opted to just fix the bug at hand and leave detection of future issues to the already open https://github.com/space-ros/docker/issues/69
=> Fix renode rcc build failure (close #170)

.github/workflows/docker-build.yml, moveit2/Dockerfile, moveit2/README.md, moveit2/build.sh, navigation2/Dockerfile, navigation2/README.md, navigation2/build.sh, space_robots/Dockerfile, space_robots/README.md
Resolves #161.
There are still issues building `main` for moveit and nav2 after migration of the base image build to the space-ros repo. This PR fixes them, including
* Updating changed environment variable names
* Fixes references to moved or removed directories in the base image
* Parameterizes the base image name for building locally and in CI
As the base `main` image is now pushed to GHCR, we should use that when building in CI. The change can be tested locally if you have access to the container registry (you _must_ be logged in):
Update:
Depends on https://github.com/space-ros/space-ros/pull/220
Because the GHCR images are not public, we can temporarily point to the main branch in the docker registry. This can be tested with either `moveit2` or `nav2` with:
```
$ docker pull …
```
=> Fix remaining issues in applications and demos from the updated spaceros base image

nav2_demo/README.md, navigation2/Dockerfile, navigation2/README.md, navigation2/docker_update_nav2_repos.sh, navigation2/excluded-pkgs.txt, navigation2/navigation2-pkgs.txt, navigation2/navigation2.repos, navigation2/src/space_nav2_bringup/CMakeLists.txt, navigation2/src/space_nav2_bringup/launch/localization_launch.py, navigation2/src/space_nav2_bringup/launch/navigation_launch.py, navigation2/src/space_nav2_bringup/package.xml, navigation2/update_nav2_repos.sh
This PR addresses: https://github.com/space-ros/docker/issues/142
This PR introduces the following changes
- Pin version of navigation2.repos to ensure reproducible builds
- Create update script according to diagram from here: https://github.com/space-ros/space-ros/discussions/166#discussioncomment-9894710. The script is called `docker_update_nav2_repos.sh`
- Simplify dockerfile
- Add `space_nav2_bringup` package allowing to launch nav2 stack (we had to get rid of nav2_bringup due to heavy dependencies such as rviz)
- Update nav2_demo accordingly -> update readme
Out of scope (will be fixed as part of different issues):
- Simplifying space_robots demo (e.g. excluding gazebo from space robots img)
- Optimizing image size of nav2 image -> will be addressed separately
- Move the docker image …
=> Pin navigation2 repos and simplify docker build (#142).

moveit2/Dockerfile
Fixes build failure of moveit2 images on Ubuntu 24.04 base images.
We luck out here, everything we need is in the apt repos, but we should revisit where these dependencies come from and why they are being installed this way.
=> Use apt install for pytest and flake8 testing libraries (fixes #213)

moveit2/Dockerfile, moveit2/README.md
Unfortunately, this repository has been flaky at best for years now. We should point users toward the Space ROS tutorials and demos, not towards the MoveIt2 demos, since a functional Canadarm demo can be a great example of motion planning with MoveIt2
=> Remove moveit2_tutorials dependency

moveit2/README.md, moveit2/build.sh
Currently, the build script for the MoveIt2 image picks `latest` as the tag, which prevents us from easily customizing the tag during the build.
This PR adjusts the build script for the MoveIt2 image to pick a tag passed in a variable as `MOVEIT2_TAG`. If the variable is not set, `latest` is used instead, defaulting to the current behavior.
The new feature is documented in the associated README.
=> Allow customizing MoveIt2 docker image tag

space_robots/Dockerfile
Fixes the Space Robots build by updating the gpg key
=> Update ROS gpg key - fix Space Robots build (#246)
